// Lightweight Qur'an API client (alquran.cloud) — Arabic only.
// Supports surah-based and page-based (Madinah Mushaf) fetching.

import { tajweedToHtml, tajweedToPlain } from "./quran-tajweed";

export type Surah = {
  number: number;
  name: string;
  englishName: string;
  englishNameTranslation: string;
  numberOfAyahs: number;
  revelationType: string;
};

export type Ayah = {
  number: number;
  numberInSurah: number;
  arabic: string;
  tajweedHtml: string;
  page: number;
  juz: number;
  surah: { number: number; name: string; englishName: string };
};

const BASE = "https://api.alquran.cloud/v1";
export const TOTAL_PAGES = 604;

let _surahCache: Surah[] | null = null;
export async function fetchSurahs(): Promise<Surah[]> {
  if (_surahCache) return _surahCache;
  const r = await fetch(`${BASE}/surah`);
  const j = await r.json();
  _surahCache = j.data as Surah[];
  return _surahCache;
}

const _pageCache = new Map<number, Ayah[]>();
export async function fetchPage(page: number): Promise<Ayah[]> {
  if (_pageCache.has(page)) return _pageCache.get(page)!;
  const r = await fetch(`${BASE}/page/${page}/quran-tajweed`);
  const j = await r.json();
  const list: Ayah[] = (j.data.ayahs as any[]).map((a) => ({
    number: a.number,
    numberInSurah: a.numberInSurah,
    arabic: tajweedToPlain(a.text),
    tajweedHtml: tajweedToHtml(a.text),
    page: a.page,
    juz: a.juz,
    surah: { number: a.surah.number, name: a.surah.name, englishName: a.surah.englishName },
  }));
  _pageCache.set(page, list);
  return list;
}

// Surah → first page (Madinah Mushaf, 1-indexed)
export const SURAH_START_PAGE: Record<number, number> = {
  1:1,2:2,3:50,4:77,5:106,6:128,7:151,8:177,9:187,10:208,11:221,12:235,13:249,14:255,15:262,
  16:267,17:282,18:293,19:305,20:312,21:322,22:332,23:342,24:350,25:359,26:367,27:377,28:385,
  29:396,30:404,31:411,32:415,33:418,34:428,35:434,36:440,37:446,38:453,39:458,40:467,41:477,
  42:483,43:489,44:496,45:499,46:502,47:507,48:511,49:515,50:518,51:520,52:523,53:526,54:528,
  55:531,56:534,57:537,58:542,59:545,60:549,61:551,62:553,63:554,64:556,65:558,66:560,67:562,
  68:564,69:566,70:568,71:570,72:572,73:574,74:575,75:577,76:578,77:580,78:582,79:583,80:585,
  81:586,82:587,83:587,84:589,85:590,86:591,87:591,88:592,89:593,90:594,91:595,92:595,93:596,
  94:596,95:597,96:597,97:598,98:598,99:599,100:599,101:600,102:600,103:601,104:601,105:601,
  106:602,107:602,108:602,109:603,110:603,111:603,112:604,113:604,114:604,
};

// Juz → first page
export const JUZ_START_PAGE: Record<number, number> = {
  1:1,2:22,3:42,4:62,5:82,6:102,7:121,8:142,9:162,10:182,11:201,12:222,13:242,14:262,15:282,
  16:302,17:322,18:342,19:362,20:382,21:402,22:422,23:442,24:462,25:482,26:502,27:522,28:542,
  29:562,30:582,
};

// Real Madani Mushaf page images (King Fahd Complex rendering, generated by quran.com-images).
// Source: github.com/GovarJabbar/Quran-PNG (mirror of quran.com-images PNG output).
// Served via jsDelivr for a fast global CDN.
export function mushafImageUrl(page: number): string {
  const p = Math.max(1, Math.min(TOTAL_PAGES, page));
  const padded = String(p).padStart(3, "0");
  return `https://cdn.jsdelivr.net/gh/GovarJabbar/Quran-PNG@master/${padded}.png`;
}

// Resolve a page → containing surah / juz.
export function pageToSurah(page: number): number {
  let last = 1;
  for (const [s, p] of Object.entries(SURAH_START_PAGE)) {
    if (p <= page) last = Number(s); else break;
  }
  return last;
}
export function pageToJuz(page: number): number {
  let last = 1;
  for (const [j, p] of Object.entries(JUZ_START_PAGE)) {
    if (p <= page) last = Number(j); else break;
  }
  return last;
}
