/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedQuranRouteImport } from './routes/_authenticated/quran'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPrayerRouteImport } from './routes/_authenticated/prayer'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as ApiPublicNotifyPrayersRouteImport } from './routes/api/public/notify-prayers'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQuranRoute = AuthenticatedQuranRouteImport.update({
  id: '/quran',
  path: '/quran',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrayerRoute = AuthenticatedPrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicNotifyPrayersRoute = ApiPublicNotifyPrayersRouteImport.update({
  id: '/api/public/notify-prayers',
  path: '/api/public/notify-prayers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/prayer': typeof AuthenticatedPrayerRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quran': typeof AuthenticatedQuranRoute
  '/api/public/notify-prayers': typeof ApiPublicNotifyPrayersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/prayer': typeof AuthenticatedPrayerRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quran': typeof AuthenticatedQuranRoute
  '/api/public/notify-prayers': typeof ApiPublicNotifyPrayersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/prayer': typeof AuthenticatedPrayerRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/quran': typeof AuthenticatedQuranRoute
  '/api/public/notify-prayers': typeof ApiPublicNotifyPrayersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/goals'
    | '/home'
    | '/prayer'
    | '/profile'
    | '/quran'
    | '/api/public/notify-prayers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/goals'
    | '/home'
    | '/prayer'
    | '/profile'
    | '/quran'
    | '/api/public/notify-prayers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/goals'
    | '/_authenticated/home'
    | '/_authenticated/prayer'
    | '/_authenticated/profile'
    | '/_authenticated/quran'
    | '/api/public/notify-prayers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicNotifyPrayersRoute: typeof ApiPublicNotifyPrayersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/quran': {
      id: '/_authenticated/quran'
      path: '/quran'
      fullPath: '/quran'
      preLoaderRoute: typeof AuthenticatedQuranRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prayer': {
      id: '/_authenticated/prayer'
      path: '/prayer'
      fullPath: '/prayer'
      preLoaderRoute: typeof AuthenticatedPrayerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/notify-prayers': {
      id: '/api/public/notify-prayers'
      path: '/api/public/notify-prayers'
      fullPath: '/api/public/notify-prayers'
      preLoaderRoute: typeof ApiPublicNotifyPrayersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedPrayerRoute: typeof AuthenticatedPrayerRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedQuranRoute: typeof AuthenticatedQuranRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedPrayerRoute: AuthenticatedPrayerRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedQuranRoute: AuthenticatedQuranRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicNotifyPrayersRoute: ApiPublicNotifyPrayersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
